### PR TITLE
Add `PIP_EXTRA_INDEX_URL` and `gh` tool to build images

### PR DESCRIPTION
**Pull request by divyegala**
Depends on https://github.com/rapidsai/gha-tools/pull/57

This PR adds:

- `PIP_EXTRA_INDEX_URL` : Environment variable for RAPIDS wheels index
- `gh` : CLI tool to generate `RAPIDS_DATE_STRING`

### CODE REVIEW

**Review by ajschmidt8 — APPROVED** [review]

**Comment by divyegala** [comment]
@ajschmidt8 could you re-review? I added `gh` tool to the images

**Review by ajschmidt8 — CHANGES_REQUESTED** [review]
Since these changes install the `gh` CLI via the OSes native package managers, the installed versions will likely be different.

To keep the versions consistent across our images, I think it might be better to install `gh` using the artifacts on their release pages: https://github.com/cli/cli/releases.

It looks like they have a tarball for each architecture (`arm64` and `amd64`) that we can extract to get the actual `gh` binary.

For now we can hardcode the version to their latest release, `2.32.0`.

When we move these images over to the `rapidsai/ci-imgs` repository, we can configure the `renovate` bot to open PRs to keep the version updated for us. See the references below for more about `renovate`:

- https://github.com/renovatebot/renovate
- https://github.com/rapidsai/ci-imgs/issues/14
- https://github.com/rapidsai/ci-imgs/pull/55

**Review by vyasr — APPROVED** [review]
Approving assuming AJ's request regarding gh CLI installation is addressed.

**Comment by ajschmidt8** [comment]
Based on the logs, it looks like Ubuntu installed the latest version (which is expected since you added the PPA), but CentOS actually didn't install any version at all:

- ubuntu - https://github.com/rapidsai/cibuildwheel-imgs/actions/runs/5601770001/jobs/10246122561?pr=29#step:8:1454
- centos - https://github.com/rapidsai/cibuildwheel-imgs/actions/runs/5601770001/jobs/10246121749?pr=29#step:8:316

**Comment by divyegala** [comment]
@ajschmidt8 do you know off the top of your head where should I unpack these tarballs so `gh` is available in `PATH` seamlessly?

**Comment by ajschmidt8** [comment]
> @ajschmidt8 do you know off the top of your head where should I unpack these tarballs so `gh` is available in `PATH` seamlessly?

`/usr/local/bin` is probably a safe bet.

**Review by ajschmidt8 — APPROVED** [review]
let's check the GHAs logs before merging this to make sure they look right, but this looks good to me.

**Pull request merged**
